### ISSUE TITLE
How can I change the **/webapps to host volumes and COPY the war to this directory auto?

### ISSUE THREAD

**Issue by flykarry** [docker-library/tomcat#140]
part of the docker-compose as blow:

 tomcat:
    build: ./tomcat
    container_name: tomcat
    ports:
      - 8080:8080
    volumes:
      - /home/docker-data/tomcat/webapps:/usr/local/tomcat/webapps
      - /home/docker-data/tomcat/logs:/usr/local/tomcat/logs

Dockerfile as blow
FROM tomcat:8.5.35-jre8-alpine
ADD demo.war /usr/local/tomcat/webapps/
COPY server.xml /usr/local/tomcat/conf/

when I run the docker-compose up, then the demo.war is not in the directory of /home/docker-data/tomcat/webapps.

**Comment by wglambert** [comment]
you're mounting a host directory over the one in the container which will overwrite any content in that directory, you could use a named volume instead or populate your mounted volume with all the content needed for its directory in the container.
```yml
version: '3'

services:
  tomcat:
   image: tomcat:test
   ports:
    - 8080:8080
   volumes:
    - webapps:/usr/local/tomcat/webapps
    - /home/docker-data/tomcat/logs:/usr/local/tomcat/logs
volumes:
  webapps:
```

```console
$ docker-compose up -d
Creating network "tomcat-140_default" with the default driver
Creating volume "tomcat-140_webapps" with default driver
Creating tomcat-140_tomcat_1 ... done

$ docker volume ls | grep webapps
local               tomcat-140_webapps

$ docker volume inspect tomcat-140_webapps 
[
    {
        "CreatedAt": "2018-12-07T10:00:08-08:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "tomcat-140",
            "com.docker.compose.volume": "webapps"
        },
        "Mountpoint": "/var/lib/docker/volumes/tomcat-140_webapps/_data",
        "Name": "tomcat-140_webapps",
        "Options": null,
        "Scope": "local"
    }
]

$ sudo ls /var/lib/docker/volumes/tomcat-140_webapps/_data
demo.war  docs  examples  host-manager  manager  ROOT
```
