### ISSUE TITLE
Problem setting locale

### ISSUE THREAD

**Issue by claudiofus** [docker-library/tomcat#189]
I think there's a problem passing values in `docker-compose.yml` because Tomcat 9 doesn't take multiple parameter from `JAVA_OPTS`.  Maybe this error is related to #77 
I have tried switching params in `JAVA_OPTS` but didn't work.

Here is my `docker-compose.yml`:
```
version: '3.7'
services:
    db:
      container_name: mariadb
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: 12345
        MYSQL_DATABASE: gestione_cantieri
      ports:
       - "3306:3306"
      volumes:
       - ./docker/db:/docker-entrypoint-initdb.d

    tomcat:
      container_name: tomcat
      image: tomcat:9.0.31-jdk13-openjdk-oracle
      environment:
       - JAVA_OPTS="-Djdbcurl=jdbc:mariadb://db:3306/MYDB?serverTimezone=UTC&amp;allowPublicKeyRetrieval=true&amp;useSSL=false -Duser.language=it -Duser.region=IT"
      ports:
       - "8000:8080"
      volumes:
       - ./docker/tomcat/GCRest.war:/usr/local/tomcat/webapps/GCRest.war
       - ./docker/tomcat/context.xml:/usr/local/tomcat/conf/context.xml
      links:
        - db
```

Here is my context.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<Context>
    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    <WatchedResource>WEB-INF/tomcat-web.xml</WatchedResource>
    <WatchedResource>${catalina.base}/conf/web.xml</WatchedResource>

	<Resource name="jdbc/MYDB"
	            auth="Container"
	            type="javax.sql.DataSource"
	            username="root"
	            password="MYPWD"
	            driverClassName="org.mariadb.jdbc.Driver"
    			url="${jdbcurl}"
	            maxTotal="8"
	            maxIdle="4"/>
</Context>
```
