### ISSUE TITLE
[tomcat:6.0.45-jre7] maxInactiveInterval not converted to seconds 

### ISSUE THREAD

**Issue by digitalLumberjack** [docker-library/tomcat#46]
Hi,
in the 6 versions of the image, the session-timeout of web.xml that is meant to be in minutes, is not converted to seconds in maxInactiveInterval.
It works on other image versions, where 30 minutes in the web.xml sets maxInactiveInterval value to 1800.

**Comment by yosifkit** [comment]
This looks like an configuration problem and is not really a problem with the images.

I can't see where `maxInactiveInterval` take a values in minutes in [tomcat 6](https://tomcat.apache.org/tomcat-6.0-doc/config/manager.html), [7](https://tomcat.apache.org/tomcat-7.0-doc/config/manager.html), or [8](https://tomcat.apache.org/tomcat-8.0-doc/config/manager.html), but only in seconds.  The only difference between the versions being a defaul value of 1800 seconds for 7 and 8, where 6 only has 60 seconds.

**Comment by digitalLumberjack** [comment]
Hi,
the maxInactiveInterval should update its value according to <session-timeout> in the web.xml.

So according to this configuration of tomcat 7 :
```
tomcat:
  ports:
    - 8080:8080
    - 6789:6789/tcp
    - 6789:6789/udp
    - 6788:6788/udp
    - 6788:6788/tcp
  image: tomcat:7-jre7
  environment:
    - CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=6788 -Dcom.sun.management.jmxremote.port=6789 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
```
After a `docker-compose up`
```
$ docker exec -ti d5799f3dce2c grep "session-timeout" /usr/local/tomcat/conf/web.xml
$ <session-timeout>30</session-timeout>
```
And the **maxInactiveInterval** equals 1800 (30*60seconds)

And according to this configuration of tomcat 6 :
```
tomcat:
  ports:
    - 8080:8080
    - 6789:6789/tcp
    - 6789:6789/udp
    - 6788:6788/udp
    - 6788:6788/tcp
  image: tomcat:6-jre7
  environment:
    - CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=6788 -Dcom.sun.management.jmxremote.port=6789 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
```
After a `docker-compose up`
```
$ docker exec -ti 8ca18cda9bc8 grep "session-timeout" /usr/local/tomcat/conf/web.xml
$ <session-timeout>30</session-timeout>
```
And the **maxInactiveInterval** equals 30.

I tried the standard image of cloudesire/tomcat:6.0-jre7 and the maxInactiveInterval is well set to 1800, with a session-timeout of 30.
