### ISSUE TITLE
ERROR: for tomcat  Cannot start service tomcat: oci runtime error: container_linux.go:265: starting container process caused "exec: \"catalina.sh\": executable file not found in $PATH"

### ISSUE THREAD

**Issue by BruceZu** [docker-library/tomcat#96]
my Dockfile is very simple
```yaml
FROM tomcat:8.0-jre8
VOLUME "/usr/local/tomcat"
```
just want to expose the tomcat home thus I can configure it and deploy war file out of the container and keep the status.

the docker-compose yaml file is very simple
```yaml
version: '3'

services:
    mysql:
        image: mysql:5.5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - mysql_data_3307:/var/lib/mysql
    tomcat: 
        build:
            context: .
            dockerfile: docker-tomcat/Dockerfile
        ports:
            - "8081:8080"
            - "8444:8443"  
        volumes:
            - ./tomcat_tmp:/usr/local/tomcat
volumes:
    mysql_data_3307:
        driver: local
```
do not know why `docker compose up` will run into the error 

```bash
$ docker-compose build && docker-compose up
Building tomcat
Step 1/2 : FROM tomcat:8.0-jre8
 ---> 0369d0b201a4
Step 2/2 : VOLUME "/usr/local/tomcat"
 ---> Running in f052de380842
 ---> d749fbdea8bf
Removing intermediate container f052de380842
Successfully built d749fbdea8bf
Successfully tagged fortipmc_tomcat:latest
mysql uses an image, skipping
Recreating fortipmc_tomcat_1
Starting fortipmc_mysql_1

ERROR: for tomcat  Cannot start service tomcat: oci runtime error: container_linux.go:265: starting container process caused "exec: \"catalina.sh\": executable file not found in $PATH"

ERROR: Encountered errors while bringing up the project.
```

**Comment by yosifkit** [comment]
You masked all of the tomcat files with your volume in the compose yaml: `./tomcat_tmp:/usr/local/tomcat`.

```console
$ docker run -it --rm tomcat bash
root@ba1c643af4af:/usr/local/tomcat# ls -l
total 120
-rw-r----- 29 root root  57092 Nov 27 13:33 LICENSE
-rw-r----- 29 root root   1723 Nov 27 13:33 NOTICE
-rw-r----- 29 root root   7138 Nov 27 13:33 RELEASE-NOTES
-rw-r----- 29 root root  16246 Nov 27 13:33 RUNNING.txt
drwxr-x---  2 root root   4096 Nov 30 23:22 bin
drwx--S---  2 root root   4096 Nov 27 13:33 conf
drwxr-sr-x  3 root staff  4096 Nov 30 23:22 include
drwxr-x---  2 root root   4096 Nov 30 23:21 lib
drwxr-x---  2 root root   4096 Nov 27 13:30 logs
drwxr-sr-x  3 root staff  4096 Nov 30 23:22 native-jni-lib
drwxr-x---  2 root root   4096 Nov 30 23:21 temp
drwxr-x---  7 root root   4096 Nov 27 13:31 webapps
drwxr-x---  2 root root   4096 Nov 27 13:30 work
```

**Comment by BruceZu** [comment]
If I use docker local volume. it works. 
```yaml
version: '3'

services:
    tomcat:
        image: tomcat:8.0-jre8 
        ports:
            - "8081:8080"
            - "8444:8443"  
        volumes:
            #- "./tomcat_home:/usr/local/tomcat"
            - tomcat_data:/usr/local/tomcat
volumes:
    mysql_data_3307:
        driver: local
    tomcat_data:
        driver: local
```

**Comment by yosifkit** [comment]
Docker treats a local volume different from a mount point. In the local volume Docker first fills the target volume (if new) with the contents of the directory from the container, but this is never done on a bind mount.

**Comment by BruceZu** [comment]
Thank you! Got it.
```yml
version: '3'

services:
    mysql:
        image: mysql:5.5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - mysql_data_3307:/var/lib/mysql
    tomcat:
        image: tomcat:8.0-jre8
        ports:
            - "8081:8080"
            - "8444:8443"
        volumes:
            - "./tomcathome/conf/server.xml:/usr/local/tomcat/conf/server.xml"
            - "./tomcathome/conf/tomcat.keystore:/usr/local/tomcat/conf/tomcat.keystore"
            - "./tomcathome/webapps/fpc/WEB-INF/classes/database.properties:/usr/local/tomcat/webapps/fpc/WEB-INF/classes/database.properties"
            - "../target/fpc:/usr/local/tomcat/webapps/fpc"
volumes:
    mysql_data_3307:
        driver: local

```
